[project]
name = "eclipse-hdr-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astropy>=8.0.1",
    "exifread>=3.5.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "opencv-python>=5.0.0.93",
    "pysiril",
    "scikit-image>=0.26.0",
    "scipy>=1.18.0",
]

[project.scripts]
eclipse-hdr = "eclipse_hdr.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
pysiril = { git = "https://gitlab.com/free-astro/pysiril.git" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]

[tool.hatch.build.targets.wheel]
packages = ["eclipse_hdr"]
